### PR TITLE
Add optional<T> data type to supported types

### PR DESCRIPTION
**Pull request by MiroPalmu**
Have optional<T> to be part of `vat` variant, where T can be int32_t, uin32_t, int64_t, uint64_t or std::string.

Example code using this feature:

```
auto input_a = std::optional<int>{ };
auto input_b = std::optional<std::string>{ };

const auto options = {
    { { "a" }, input_a, "Input a"},
    { { "b" }, input_b, "input_b"}
};

argz::parse(about, opts, argc, argv);

if (input_a) foo(input_a.value());
if (input_b) bar(input_b.value());

```

Notice that T can not be bool due to ambiguous meaning in the following example:

```
auto bool_opt = std::optional<bool>{ };

const auto options = {
    { { "a" }, bool_opt, "Input a"}
};

argz::parse(about, opts, argc, argv);

// Now if command line is: "./prog -a"
// should input_a be empty or contain true?

if (input_a) foo(input_a.value());

````

If optional would contain integer or string input_a would be empty optional.

### CODE REVIEW

**Comment by MiroPalmu** [comment]
Force push was to remove redundant construction of std::reference_wrapper which got implicitly converted to normal reference immediately.

**Comment by stephenberry** [comment]
@MiroPalmu
This is brilliant! I made a tiny fix to build with clang. But, thanks so much for this addition.

**Comment by MiroPalmu** [comment]
@stephenberry 

I realized one complication about this. [Templated/generic lambdas](https://en.cppreference.com/w/cpp/language/lambda) were added in c++20 and CMakeLists.txt at the moment has `target_compile_features(argz_argz INTERFACE cxx_std_17)`

This was not apparent when I was testing this because CMake somehow selects c++20 automatically for me.

**Comment by stephenberry** [comment]
@MiroPalmu 
Ah, thanks for pointing this out. I'm fine moving to a C++20 requirement. All my other projects are moving to this requirement and I find C++20 to be widely available now. I'll update accordingly.

**Pull request merged**
